# .github/workflows/audit.yml
name: Security Audit

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 0' # every Sunday at 3:00 UTC

permissions:
  contents: read
  pull-requests: write

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2025-03-26
          components: rust-src, llvm-tools-preview

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Run cargo audit
        run: cargo audit
